---

- name: postgres-cluster-setup
  gather_facts: true
  hosts: nodes
  become: yes
  tasks:
    - name: Add an PostgreSQL apt signing key
      become: yes
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add PostgreSQL repo
      become: yes
      apt_repository:
        repo: "deb https://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
        state: present
        filename: pgdg

    - name: install Postgres packages
      become: yes
      apt:
        name:
          - postgresql-16
          - postgresql-contrib
        state: present

    - name: disable postgresql service autostart (will be managed by Patroni)
      become: yes
      service:
        name: postgresql
        enabled: no
        
    - name: stop postgresql service on slave (will be managed by Patroni)
      become: yes
      service:
        name: postgresql
        state: stopped

    - name : Register files under postgres bin directory
      find:
        paths: /usr/lib/postgresql/16/bin
        file_type : file
      register: output

    - name: Create softlink to postgresql 16 version
      become: yes
      file:
        src: "{{ item.path }}"
        dest: "/usr/sbin/{{ item.path | basename }}"
        state: link
      with_items: "{{ output.files }}"
    
    - name: Install python3, patroni and other packages
      become: yes
      apt:
        name:
          - python3-pip
          - python3-dev
          - libpq-dev
          - python3-etcd
          - patroni
        state: present

    - name: Create patroni configuration file
      become: yes
      template:
        src: patroni.cfg
        dest: /etc/patroni/patroni.yml
    
    - name: create DataDir on both nodes and set file permission
      become: yes
      file:
        path: /opt/data/patroni
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Create patroni service file on both nodes
      copy:
        src: patroni.service
        dest: /etc/systemd/system/patroni.service

- name: Setup etcd on ETCD host
  gather_facts: true
  hosts: etcd01
  become: yes
  tasks:
    - name: Add PostgreSQL repo
      become: yes
      apt_repository:
        repo: "deb http://deb.debian.org/debian bullseye main contrib non-free"
        state: present
        filename: sources

    - name: Install etcd package
      become: yes
      apt:
        name:
          - etcd
        state: present

    - name: Create etcd configuration file
      become: yes
      template:
        src: etcd.cfg
        dest: /etc/default/etcd

    - name: Restart etcd service
      become: yes
      systemd:
        name: etcd
        state: restarted

- name: Startup patroni and postgres services
  gather_facts: true
  hosts: nodes
  become: yes
  tasks:
    - name: start patroni service
      become: yes
      systemd:
        name: patroni
        state: started

    - name: start postgres service
      become: yes
      systemd:
        name: postgresql
        state: started